### ISSUE TITLE
Doubling polls on the frontend

### ISSUE THREAD

**Issue by ducdhm** [ducdhm/kpoll#1]
![dd266f0c-7263-11e5-9ea7-4ccaf3ef8628](https://cloud.githubusercontent.com/assets/1289631/10480933/8cee09bc-7297-11e5-9bdc-51de9813eabd.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/10559114/f1e6f5d0-74f0-11e5-925f-7569adcb8a70.png)
Still the same

**Comment by ducdhm** [comment]
@Uafinder Can you show me how to reproduce this bug?

**Comment by ducdhm** [comment]
Let's move to https://github.com/ducdhm/kpoll/issues/18
